version: 2.1
jobs:
  build:
    working_directory: ~/angular-jozi-js
    docker:
      - image: circleci/node:10-browsers # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world"
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
            # Install project dependencies
            - run:
                name: Install local dependencies
                command: npm install
