version: 2.1
orbs:
  node: circleci/node@1.1.6
  browser-tools: circleci/browser-tools@1.0.1
jobs:
  build-and-test:
    docker:
      - image: 'cimg/node:13.12'
    executor:
      name: node/default
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
  build-and-test:
    jobs:
      - build-and-test
