version: 2
jobs:
  build:
    working_directory: ~/angular-jozi-js
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: angular-jozi-js-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: angular-jozi-js-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"

      - run:
          name: Lint
          command: npm run ng lint
      - run:
          name: Unit Test
          command: npm run ng test -- --watch=false --code-coverage
      - run:
          name: Coveralls
          command: cat ./coverage/angular-jozi-js/lcov.info  | ./node_modules/coveralls/bin/coveralls.js

